In [ ]:
Python DA Assignment 1: Data Analysis using

NumPy and Pandas

Numpy Array Operations:
Problem Statement: To learn how to use NumPy for creating arrays, performing basic
array operations, and conducting numerical computations through analyzing
temperature data.

Scenario: You are given a list of daily average temperatures (in degrees Celsius)
recorded over two weeks. Your task is to use NumPy to analyze this data.
Step wise Instructions:

1. Create a 1D NumPy Array:
Create a 1D NumPy array named temperatures_w1 for Week 1 with the
following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [2]:
import numpy as np

In [ ]:
NumPy is imported for creating array.

In [3]:
temperatures_w1=np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
A one dimensional array is created using numpy.

In [ ]:
2. Inspection and Properties:
● Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.

In [5]:
temperatures_w1.shape

(7,)

In [ ]:
By using .shape keyword it is clear that temperatures_w1 is a one dimensional array contains 1 row and 7 columns.

In [6]:
temperatures_w1.dtype

dtype('float64')

In [7]:
temperatures_w1.size

7

In [ ]:
It is clear that the array contains 7 elements in it.

In [9]:
temperatures_w1.ndim

1

In [ ]:
3. Array Operations:
● Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32
● Find the maximum, minimum, and mean temperatures for the week.

In [13]:

fahrenheit=np.array((temperatures_w1*9/5)+32)
fahrenheit

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [19]:
maximum_temperature=np.max(temperatures_w1)
print("Maximum temperature of the week: ",maximum_temperature)

Maximum temperature of the week:  26.1

In [ ]:
Using max() keyword the greatest temperature from this week is identified.

In [20]:
minimum_temperature=np.min(temperatures_w1)
print("Minimum temperature of the week : ",minimum_temperature)

Minimum temperature of the week :  20.8

In [ ]:
Using min() keyword the lowest temperature from the week is identified.

In [18]:
mean_temperature=np.mean(temperatures_w1)
print("mean_temperature of the week: ",mean_temperature)

mean_temperature of the week:  23.542857142857144

In [ ]:
The average of the temperature from this week is calculated using mean() keyword.

In [ ]:
4. Array Slicing and Indexing:
● Extract the temperatures for the first three days of the week.
● Extract the temperatures for the weekend (last two days).
● Extract the temperatures for the middle three days of the week.

In [23]:
print("Temperatures for the first 3 days of the week :",temperatures_w1[0:3])

Temperatures for the first 3 days of the week : [22.5 25.3 20.8]

In [27]:
print("Temperatures for the weekend(last 2 days) :",temperatures_w1[5:])

Temperatures for the weekend(last 2 days) : [24.8 21.9]

In [28]:
print("Temperatures for the middle 3 days of the week :",temperatures_w1[2:5])

Temperatures for the middle 3 days of the week : [20.8 23.4 26.1]

In [ ]:
Using positive indexing slicing, temperatures from the week is sliced.

In [ ]:
5. Create a 2D Array:
Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:
★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [30]:
temperatures=np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9],[19.2,22.5,21.3,24.0,23.5,22.8,20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [ ]:
A two dimensional array is created using numpy.

In [ ]:
6. Inspect and Slice the 2D Array:
● Inspect and print the shape, data type, and total number of elements in the
temperatures array.
● Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [31]:
temperatures.shape

(2, 7)

In [ ]:
From the shape keyword it is clear that the 2dimensional array contains 2 rows and 7 columns in it.

In [32]:
temperatures.dtype

dtype('float64')

In [34]:
temperatures.size

14

In [ ]:
From the size keyword it is clear that a total of 14 elements are present in the 2d array.

In [39]:
print("Temperatures for the week1: ",temperatures[0:1,0:])

Temperatures for the week1:  [[22.5 25.3 20.8 23.4 26.1 24.8 21.9]]

In [40]:
print("Temperatures for the week2: ",temperatures[1:,0:])

Temperatures for the week2:  [[19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [41]:
print("Temperatures for the weekend of week1: ",temperatures[0:1,5:])

Temperatures for the weekend of week1:  [[24.8 21.9]]

In [42]:
print("Temperatures for the weekend of week1: ",temperatures[1:,5:])

Temperatures for the weekend of week1:  [[22.8 20.1]]

In [ ]:
By using positivie indexing slicing different temperatures from different weeks are sliced from this 2d array.

In [ ]:
Pandas Series:
1. Creating Pandas Series:
● Create a Pandas Series named marks with the following data:
➢ Marks: 95, 92, 89, 85, 80
➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [43]:
import pandas as pd

In [ ]:
Pandas are imported from series and dataframe creation and operations.

In [45]:
marks=pd.Series([95,92,89,85,80],index=("Rank1","Rank2","Rank3","Rank4","Rank5"))
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [ ]:
A series is created with customized index.

In [ ]:
2. Indexing and Slicing:
● Use the integer index position to access the mark of the 1st rank student.

In [47]:
print("Mark of the 1st rank student: ",marks.iloc[0])

Mark of the 1st rank student:  95

In [ ]:
Here iloc is used for the assessing of 1st rank mark, since iloc is an  index based positioning method, index is used here.

In [ ]:
● Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.

In [50]:
print("Marks of the top 3 ranks: ", marks.loc["Rank1":"Rank3"])

Marks of the top 3 ranks:  Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [ ]:
Since loc is a label based accessor the labels are used with loc for slicing.

In [ ]:
● Use the iloc accessor to retrieve the mark of the 3rd rank student.

In [51]:
print("Mark of the 3rd rank student: ",marks.iloc[2])

Mark of the 3rd rank student:  89

In [ ]:
Since iloc is used here so index is used for retreival.

In [ ]:
● Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.

In [53]:
print("The ranks have higher marks than 90: ", marks[(marks>90)])

The ranks have higher marks than 90:  Rank1    95
Rank2    92
dtype: int64

In [ ]:
We need to filter things with certain conditions so we applied boolean filtering here.

In [ ]:
3. Manipulating Series:
● Modify the mark of the student with the 1st rank to 100.

In [73]:
marks["Rank1"]=100
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
Here marks is modified in the specific index position by using label index of the marks.

In [ ]:
● Remove the entry corresponding to the last rank from the Series.

In [81]:
marks=marks.drop(["Rank5"])

In [82]:
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [ ]:
Drop keyword is used here to remove the last entry of marks.

In [ ]:
● Compute the CGPA by dividing each mark in the Series by 10.

In [83]:
CGPA=marks/10
print("CGPA OF MARKS: ",CGPA)

CGPA OF MARKS:  Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [ ]:
Pandas DataFrame:
1. Creating Pandas DataFrame:
● Create a Pandas DataFrame named transactions with the following data:
➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'
➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [212]:
Transactions=pd.DataFrame({"TransactionID":[101,102,103,104,105,106,107,108,109,110],
                           "ProductCategory":['Electronics','Clothing','Electronics','Furniture','Clothing','Electronics','Furniture','Clothing','Furniture','Electronics'],
                           "Region":['North','South','North','East','West','North','East','West','South','North'],
                           "Amount":[200,150,300,450,200,250,300,180,350,400]})

In [ ]:
Using pandas dataframe Transactions is created here.

In [ ]:
2. Data Exploration:
● Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.

In [213]:
Transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [214]:
Transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [ ]:
Head() keyword retreives the first 5 rows from the dataframe.

In [215]:
Transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
The tail() keyword retreives the last 5 rows from the dataframe.

In [216]:
Transactions.shape

(10, 4)

In [ ]:
shape keyword provides the shape of the dataframe i.e; 10 rows and 4 columns.

In [217]:
Transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [ ]:
columns keyword gives all the columns from the dataframe.

In [218]:
Transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [ ]:
dtypes keyword gives datatypes of each columns from the dataframe.

In [ ]:
● Display only the 'ProductCategory' and 'Amount' columns.

In [219]:
print(Transactions[["ProductCategory","Amount"]])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
for accessing 2 columns from the dataframe 2 [[]] are used here.

In [ ]:
● Retrieve the last 3 columns of the DataFrame using iloc or loc.

In [220]:
print(Transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
Here iloc is used to retreive 3 columns from dataframe, so index positions are used here, since iloc works based on index.The index[:] shows the full rows, index[-3:] represents the last 3 columns from the dataframe.

In [ ]:
● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [221]:
print(Transactions[(Transactions["Region"]=="North") & (Transactions["Amount"]>200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
Here boolean filtering is used along with & because the 2 conditions has to merge here for the filtering.

In [ ]:
● Find the value counts for the 'ProductCategory' column.

In [222]:
Transactions.value_counts("ProductCategory")

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:
Here value_count() keyword is used for getting the counts of each values in productcategory column.

In [ ]:
● Find the unique values in the 'Region' column.

In [223]:
Transactions["Region"].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [ ]:
Here unique() keyword is used finding distinct values in the column region.

In [ ]:
● Group by 'Region' and find the mean amount for each region.

In [224]:
Transactions.groupby("Region")["Amount"].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [ ]:
Groupby is used inside region column and aggregation is used inside amount column and finally got mean amount for each region.

In [ ]:
3. Manipulating the DataFrame:
● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

In [225]:
Transactions.loc[Transactions["TransactionID"]==102,"Amount"]=165

In [ ]:
Loc is used here for the updation of amount in a specific transactionID, because loc is a label based accessor .

In [226]:
Transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
Successfully the amount is updated to the dataframe.

In [ ]:
● Add a new column 'Discount' by calculating 10% of the 'Amount'.

In [227]:
Transactions["Discount"]=Transactions["Amount"]*10/100

In [228]:
Transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [ ]:
The new column Discount is successfully added to the dataframe using the above formula.

In [ ]:
● Remove the row with TransactionID 109.

In [231]:
Transactions=Transactions.drop(Transactions[Transactions["TransactionID"]==109].index)

In [ ]:
Drop keyword along with index is used here to remove the specific row.Index is used here for preserving the others index properly in the dataframe.

In [232]:
Transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [ ]:
● Delete the 'Discount' column from the DataFrame.

In [233]:
Transactions.drop(columns=["Discount"],inplace=True)

In [234]:
Transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [ ]:
Using drop keyword the column Discount is removed from the dataframe. Inplace is used for the permenant removal of the column from dataframe.

In [235]:
Transactions.to_csv("Cleaned_Transactions",index=False)